# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.8
_src_path: https://github.com/jupyterlab/extension-template
author_email: hunt.ant137@gmail.com
author_name: Anthony Hunt
has_binder: false
has_settings: false
kind: frontend
labextension_name: simile_lexer
project_short_description: CodeMirror lexer for Simile
python_name: simile_lexer
repository: ''
test: true

