from functools import singledispatchmethod
from dataclasses import dataclass, field

from src.mod.data import ast_


@dataclass
class StructuralMatch:
    match_identifier_names: set[str]

    matched_so_far: dict[str, ast_.ASTNode] = field(default_factory=lambda: {})

    def structural_match(self, ast: ast_.ASTFieldChildren, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None:
        if not isinstance(ast, ast_.ASTNode) or not isinstance(against, ast_.Identifier) or against.name not in self.match_identifier_names:
            return self._structural_match(ast, against)
        # Identifiers can match any part of the ast: Ex. match (2 + 3) to an identifier
        if against.name not in self.matched_so_far:
            self.matched_so_far[against.name] = ast
        if self.matched_so_far[against.name] == ast:
            return self.matched_so_far
        return None

    @singledispatchmethod
    def _structural_match(self, ast: ast_.ASTFieldChildren, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None:
        raise NotImplementedError(f"Structural match not implemented for {type(ast)}")

    @_structural_match.register
    def _(self, ast: ast_.Primitive, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None:
        if isinstance(against, ast_.Primitive) and ast == against:
            return {}
        return None

    @_structural_match.register
    def _(self, ast: ast_.Primitive, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None:
        if isinstance(against, ast_.Primitive) and ast == against:
            return {}
        return None

    @_structural_match.register
    def _(self, ast: ast_.BinaryOp, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.RelationOp, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.UnaryOp, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.ListOp, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.Quantifier3, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.Generator, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.QuantifierBody, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.Fold, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.IterGenerator, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.IterBodyEnd, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.IterBody, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.Iter, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.Enumeration, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.Type_, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.LambdaDef, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.RecordAccess, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.Call, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.Image, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.TypedName, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.Assignment, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.TraitApplication, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.Return, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.ControlFlowStmt, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.Statements, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.Else, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.If, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.ElseIf, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.For, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.While, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.RecordDefIdentifier, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.RecordDefSymbol, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.TupleLiteral, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.ProcedureDefIdentifier, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.ProcedureDefSymbol, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.Import, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.Start, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...

    ### pre_symbol_table ###
    @_structural_match.register
    def _(self, ast: ast_.Identifier, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.TupleIdentifier, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.MapletIdentifier, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...

    ### post_symbol_table ###
    @_structural_match.register
    def _(self, ast: ast_.Symbol, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.TupleSymbol, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.MapletSymbol, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...

    ### post_optimizer ###
    @_structural_match.register
    def _(self, ast: ast_.GeneratorSelection, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.CombinedGeneratorSelection, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.SingleGeneratorSelection, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
    @_structural_match.register
    def _(self, ast: ast_.Loop, against: ast_.ASTFieldChildren) -> dict[str, ast_.ASTNode] | None: ...
