from dataclasses import dataclass, fields, field
from functools import singledispatch


from src.mod.data.ast_.operators import UnaryOperator
from src.mod.data.ast_.base import ASTNode
from src.mod.data.ast_.parser_only import (
    Identifier,
    MapletIdentifier,
    TupleIdentifier,
)
from src.mod.data.ast_.common import (
    Int,
    Float,
    String,
    True_,
    False_,
    None_,
    BinaryOp,
    RelationOp,
    UnaryOp,
    ListOp,
    Quantifier3,
    QuantifierBody,
    Generator,
    Fold,
    IterGenerator,
    IterBodyEnd,
    IterBody,
    Iter,
    TraitApplication,
    ControlFlowStmt,
    Enumeration,
    Type_,
    LambdaDef,
    RecordAccess,
    Call,
    TypedName,
    Image,
    Assignment,
    Return,
    Statements,
    Else,
    If,
    ElseIf,
    For,
    While,
    RecordDef,
    ProcedureDef,
    Import,
    Start,
    TupleLiteral,
)
from src.mod.data.ast_.operators import ImportOperator
from src.mod.data.ast_.optimizer_only import (
    GeneratorSelection,
    CombinedGeneratorSelection,
    SingleGeneratorSelection,
    Loop,
)


def ast_to_source(ast: ASTNode) -> str:
    """Convert an AST node back to its source code representation."""
    return _ast_to_source(ast, 0)


@singledispatch
def _ast_to_source(ast: ASTNode, indent: int) -> str:
    raise Exception(f"Compiler error: missing ast_to_source definition for AST type {ast.__class__.__name__}", ast)


@_ast_to_source.register(Identifier)
def _(ast: Identifier, indent: int) -> str:
    # TODO remove special case for identifier - reassigned/autogenerated variables should use a different AST type
    if ast.name.startswith("*"):
        return f"x{''.join(filter(str.isnumeric, ast.name))}"
    return ast.name


@_ast_to_source.register(TupleIdentifier)
def _(ast: TupleIdentifier, indent: int) -> str:
    if len(ast.items) == 1:
        return _ast_to_source(ast.items[0], indent)
    return f"({', '.join(_ast_to_source(item, indent) for item in ast.items)})"


@_ast_to_source.register(MapletIdentifier)
def _(ast: MapletIdentifier, indent: int) -> str:
    return f"{_ast_to_source(ast.left, indent)} ↦ {_ast_to_source(ast.right, indent)}"


@_ast_to_source.register(Int)
@_ast_to_source.register(Float)
@_ast_to_source.register(String)
def _(ast: Int | Float | String, indent: int) -> str:
    return ast.value


@_ast_to_source.register(True_)
def _(ast: True_, indent: int) -> str:
    return "True"


@_ast_to_source.register(False_)
def _(ast: False_, indent: int) -> str:
    return "False"


@_ast_to_source.register(None_)
def _(ast: None_, indent: int) -> str:
    return "None"


@_ast_to_source.register(BinaryOp)
@_ast_to_source.register(RelationOp)
def _(ast: BinaryOp | RelationOp, indent: int) -> str:
    left_str = _ast_to_source(ast.left, indent)
    right_str = _ast_to_source(ast.right, indent)
    return f"({left_str} {ast.op_type.to_source()} {right_str})"


@_ast_to_source.register(UnaryOp)
def _(ast: UnaryOp, indent: int) -> str:
    if ast.op_type == UnaryOperator.INVERSE:
        return f"{_ast_to_source(ast.value, indent)}{ast.op_type.to_source()}"
    return f"{ast.op_type.to_source()}{_ast_to_source(ast.value, indent)}"


@_ast_to_source.register(ListOp)
def _(ast: ListOp, indent: int) -> str:
    if len(ast.items) == 0:
        return ""
    if len(ast.items) == 1:
        return _ast_to_source(ast.items[0], indent)
    return "(" + f" {ast.op_type.to_source()} ".join(_ast_to_source(item, indent) for item in ast.items) + ")"


@_ast_to_source.register(Quantifier3)
def _(ast: Quantifier3, indent: int) -> str:
    quantifier = _ast_to_source(ast.body, indent)

    if ast.op_type.is_collection_operator():  # collection operators need to wrap the quantification
        l_wrapper, r_wrapper = tuple(ast.op_type.to_source())
        quantifier = f"{l_wrapper}{quantifier}{r_wrapper}"
    else:
        quantifier = f"{ast.op_type.to_source()} {quantifier}"
    return quantifier


@_ast_to_source.register(Generator)
def _(ast: Generator, indent: int) -> str:
    generator = f"{_ast_to_source(ast.identifiers, indent)} ∈ {_ast_to_source(ast.set_, indent)}"
    if not isinstance(ast.predicate, True_):
        generator += f" · {_ast_to_source(ast.predicate, indent)}"
    return generator


@_ast_to_source.register(QuantifierBody)
@_ast_to_source.register(IterBody)
def _(ast: QuantifierBody | IterBody, indent: int) -> str:
    generators = ", ".join(_ast_to_source(gen, indent) for gen in ast.generators)
    if isinstance(ast.end_or_branch, list):
        # To account for no initial generators, we conditionally add a comma between generators and branches
        if generators:
            generators += ", "
        branches = ") ` (".join(_ast_to_source(branch, indent) for branch in ast.end_or_branch)
        return f"{generators}({branches})"
    return f"{generators} | {_ast_to_source(ast.end_or_branch, indent)}"


@_ast_to_source.register(Fold)
def _(ast: Fold, indent: int) -> str:
    init_accumulator = _ast_to_source(ast.accumulator_init, indent)
    body = _ast_to_source(ast.quantifier_body, indent)
    return f"fold {init_accumulator} : {body}"


@_ast_to_source.register(IterGenerator)
def _(ast: IterGenerator, indent: int) -> str:
    assignments = "; ".join(_ast_to_source(assignment, indent) for assignment in ast.assignments)
    return f"{_ast_to_source(ast.generator, indent)} : {assignments}"


@_ast_to_source.register(IterBodyEnd)
def _(ast: IterBodyEnd, indent: int) -> str:
    body = _ast_to_source(ast.body, indent)
    return_value = _ast_to_source(ast.return_value, indent)
    return f"→ {return_value} | {body}"


@_ast_to_source.register(Iter)
def _(ast: Iter, indent: int) -> str:
    return f"iter {ast.body}"


@_ast_to_source.register(Enumeration)
def _(ast: Enumeration, indent: int) -> str:
    l_wrapper, r_wrapper = tuple(ast.op_type.to_source())
    return f"{l_wrapper}{', '.join(_ast_to_source(item, indent) for item in ast.items)}{r_wrapper}"


@_ast_to_source.register(TupleLiteral)
def _(ast: TupleLiteral, indent: int) -> str:
    if len(ast.items) == 1:
        return f"({_ast_to_source(ast.items[0], indent)},)"
    return f"({', '.join(_ast_to_source(item, indent) for item in ast.items)})"


@_ast_to_source.register(Type_)
def _(ast: Type_, indent: int) -> str:
    generic_parameters = [_ast_to_source(param, indent) for param in ast.generics]
    if not generic_parameters:
        return _ast_to_source(ast.type_, indent)
    return f"{_ast_to_source(ast.type_, indent)}[{', '.join(generic_parameters)}]"


@_ast_to_source.register(LambdaDef)
def _(ast: LambdaDef, indent: int) -> str:
    args_str = _ast_to_source(ast.params, indent)
    predicate_str = _ast_to_source(ast.predicate, indent)
    expression_str = _ast_to_source(ast.expression, indent)
    return f"λ {args_str} · {predicate_str} | {expression_str}"


@_ast_to_source.register(RecordAccess)
def _(ast: RecordAccess, indent: int) -> str:
    return f"{_ast_to_source(ast.record, indent)}.{_ast_to_source(ast.field_name, indent)}"


@_ast_to_source.register(Call)
def _(ast: Call, indent: int) -> str:
    args_str = ", ".join(_ast_to_source(arg, indent) for arg in ast.args)
    return f"{_ast_to_source(ast.target, indent)}({args_str})"


@_ast_to_source.register(Image)
def _(ast: Image, indent: int) -> str:
    args_str = ", ".join(_ast_to_source(arg, indent) for arg in ast.indices)
    return f"{_ast_to_source(ast.target, indent)}[{args_str}]"


@_ast_to_source.register(TypedName)
def _(ast: TypedName, indent: int) -> str:
    return f"{_ast_to_source(ast.name, indent)}: {_ast_to_source(ast.type_, indent)}"


@_ast_to_source.register(TraitApplication)
def _(ast: TraitApplication, indent: int) -> str:
    target = _ast_to_source(ast.target, indent)
    if ast.traits:
        indentation = "\t" * (indent + 1)
        with_clause_str = f"\n{indentation}with" + f"\n{indentation}with".join(_ast_to_source(clause, indent + 1) for clause in ast.traits)
        return f"{target}{with_clause_str}"
    return target


@_ast_to_source.register(Assignment)
def _(ast: Assignment, indent: int) -> str:
    if ast.choice_assignment:
        return f"{_ast_to_source(ast.target, indent)} :∈ {_ast_to_source(ast.value, indent)}"
    return f"{_ast_to_source(ast.target, indent)} := {_ast_to_source(ast.value, indent)}"


@_ast_to_source.register(Return)
def _(ast: Return, indent: int) -> str:
    if isinstance(ast.value, None_):
        return "return"
    return f"return {_ast_to_source(ast.value, indent)}"


@_ast_to_source.register(ControlFlowStmt)
def _(ast: ControlFlowStmt, indent: int) -> str:
    return ast.op_type.to_source()


@_ast_to_source.register(Statements)
def _(ast: Statements, indent: int) -> str:
    return f"\n{'\t'*indent}".join(_ast_to_source(item, indent) for item in ast.items)


@_ast_to_source.register(Else)
def _(ast: Else, indent: int) -> str:
    return f"else:\n\t{'\t'*indent}{_ast_to_source(ast.body, indent+1)}\n"


@_ast_to_source.register(If)
def _(ast: If, indent: int) -> str:
    ret = f"if {_ast_to_source(ast.condition, indent)}:\n"
    ret += f"{'\t' * (indent + 1)}{_ast_to_source(ast.body, indent + 1)}"
    ret += "\n"
    if isinstance(ast.else_body, None_):
        return ret
    ret += _ast_to_source(ast.else_body, indent)
    return ret


@_ast_to_source.register(ElseIf)
def _(ast: ElseIf, indent: int) -> str:
    ret = f"else if {_ast_to_source(ast.condition, indent)}:\n"
    ret += f"{'\t' * (indent + 1)}{_ast_to_source(ast.body, indent + 1)}"
    ret += "\n"
    if isinstance(ast.else_body, None_):
        return ret
    ret += _ast_to_source(ast.else_body, indent)
    return ret


@_ast_to_source.register(For)
def _(ast: For, indent: int) -> str:
    iterable_str = _ast_to_source(ast.iterable, indent)
    names_str = _ast_to_source(ast.iterable_names, indent)
    body_str = _ast_to_source(ast.body, indent + 1)
    return f"for {names_str} in {iterable_str}:\n{'\t' * (indent + 1)}{body_str}\n"


@_ast_to_source.register(While)
def _(ast: While, indent: int) -> str:
    condition_str = _ast_to_source(ast.condition, indent)
    body_str = _ast_to_source(ast.body, indent + 1)
    return f"while {condition_str}:\n{'\t' * (indent + 1)}{body_str}\n"


@_ast_to_source.register(RecordDef)
def _(ast: RecordDef, indent: int) -> str:
    items_str = f"\n{'\t'*(indent + 1)}".join(_ast_to_source(item, indent + 1) for item in ast.items)
    return f"struct {_ast_to_source(ast.name, indent)}({items_str})"


@_ast_to_source.register(ProcedureDef)
def _(ast: ProcedureDef, indent: int) -> str:
    args_str = f",\n{'\t'*(indent + 1)}".join(_ast_to_source(arg, indent + 1) for arg in ast.args)
    body_str = _ast_to_source(ast.body, indent + 1)
    return_type_str = _ast_to_source(ast.return_type, indent)
    return f"def {_ast_to_source(ast.name, indent)}(\n{args_str}\n) -> {return_type_str}:\n{'\t' * (indent + 1)}{body_str}\n"


@_ast_to_source.register(Import)
def _(ast: Import, indent: int) -> str:
    match ast.operator:
        case ImportOperator.ALL_NAMES:
            return f"from {ast.module_file_path} import *"
        case ImportOperator.MODULE_NAME:
            return f"import {ast.module_file_path}"
        case ImportOperator.SPECIFIC_NAMES:
            return f"from {ast.module_file_path} import {', '.join(ast.import_objects)}"


@_ast_to_source.register(Start)
def _(ast: Start, indent: int) -> str:
    return _ast_to_source(ast.body, indent) if ast.body else ""


@_ast_to_source.register(GeneratorSelection)
@_ast_to_source.register(CombinedGeneratorSelection)
@_ast_to_source.register(SingleGeneratorSelection)
def _(ast: GeneratorSelection | CombinedGeneratorSelection | SingleGeneratorSelection, indent: int) -> str:
    return _ast_to_source(ast.flatten(), indent)


@_ast_to_source.register(Loop)
def _(ast: Loop, indent: int) -> str:
    predicate = _ast_to_source(ast.predicate, indent)
    body = _ast_to_source(ast.body, indent + 1)
    return f"loop {predicate}:\n{'\t' * (indent + 1)}{body}\n"


def ast_to_debug_string(
    ast: ASTNode,
    ignore_fields: list[str] | None = None,
) -> str:
    """Pretty print the AST node with JSON-like indentation for debugging."""
    if ignore_fields is None:
        ignore_fields = []
    # TODO check should indent=2?
    return _ast_to_debug_string(ast, ignore_fields, 0)


def _ast_to_debug_string(
    ast: ASTNode,
    ignore_fields: list[str],
    indent: int,
) -> str:
    if ast.__class__.__name__ in ignore_fields:
        indent_ = ""
        indent -= 2
        ret = ""
    else:
        ret = f"{ast.__class__.__name__}:\n"
        indent_ = indent * " "

    for f in fields(ast):
        field_value = getattr(ast, f.name)

        if isinstance(field_value, ASTNode):
            if len(fields(ast)) == 1:
                ret += f"{indent_}{_ast_to_debug_string(field_value, ignore_fields, indent + 2)}"
            else:
                ret += f"{indent_}{f.name}={_ast_to_debug_string(field_value,ignore_fields,indent + 2)}"

            continue

        if isinstance(field_value, list):
            ret += f"{indent_}[\n"
            for item in field_value:
                if isinstance(item, ASTNode):
                    ret += f"{indent_}{_ast_to_debug_string(item,ignore_fields,indent + 2)}"
                else:
                    ret += f"{indent_}    {item}\n"
            ret += f"{indent_}]\n"
            continue

        ret += f"- {indent_}{f.name}: {field_value}\n"
    return ret
