[build-system]
requires = ["hatchling>=1.10.0", "ipykernel"]
build-backend = "hatchling.build"

[project]
name = "simile-jupyter-kernel"
dynamic = ["version"]
description = "Interactive kernel for Simile"
readme = "README.md"
license = { file = "LICENSE" }
authors = [{ name = "Anthony Hunt", email = "hunt.ant137@gmail.com" }]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.8"
dependencies = ["ipykernel", "jupyter_client", "simile_compiler"]

# [project.optional-dependencies]
# test = ["jupyter_kernel_test"]

# [project.urls]
# Homepage = "https://github.com/jupyter/echo_kernel"

[tool.hatch.version]
path = "simile_jupyter_kernel/__init__.py"

# Used to call hatch_build.py
[tool.hatch.build.hooks.custom]


[tool.hatch.build.targets.sdist]
include = ["/simile_jupyter_kernel"]

[tool.hatch.build.targets.wheel.shared-data]
"data_kernelspec/share" = "share"
