from dataclasses import fields
from functools import singledispatch

from src.mod.data import ast_


def ast_to_source(ast: ast_.ASTNode) -> str:
    """Convert an AST node back to its source code representation."""
    return _ast_to_source(ast, 0)


@singledispatch
def _ast_to_source(ast: ast_.ASTNode, indent: int) -> str:
    raise Exception(f"Compiler error: missing ast_to_source definition for AST type {ast.__class__.__name__}", ast)


@_ast_to_source.register(ast_.Identifier)
def _(ast: ast_.Identifier, indent: int) -> str:
    # TODO remove special case for identifier - reassigned/autogenerated variables should use a different AST type
    if ast.name.startswith("*"):
        return f"x{''.join(filter(str.isnumeric, ast.name))}"
    return ast.name


@_ast_to_source.register(ast_.TupleIdentifier)
def _(ast: ast_.TupleIdentifier, indent: int) -> str:
    if len(ast.items) == 1:
        return _ast_to_source(ast.items[0], indent)
    return f"({', '.join(_ast_to_source(item, indent) for item in ast.items)})"


@_ast_to_source.register(ast_.MapletIdentifier)
def _(ast: ast_.MapletIdentifier, indent: int) -> str:
    return f"{_ast_to_source(ast.left, indent)} ↦ {_ast_to_source(ast.right, indent)}"


@_ast_to_source.register(ast_.Int)
@_ast_to_source.register(ast_.Float)
@_ast_to_source.register(ast_.String)
def _(ast: ast_.Int | ast_.Float | ast_.String, indent: int) -> str:
    return ast.value


@_ast_to_source.register(ast_.True_)
def _(ast: ast_.True_, indent: int) -> str:
    return "True"


@_ast_to_source.register(ast_.False_)
def _(ast: ast_.False_, indent: int) -> str:
    return "False"


@_ast_to_source.register(ast_.None_)
def _(ast: ast_.None_, indent: int) -> str:
    return "None"


@_ast_to_source.register(ast_.BinaryOp)
@_ast_to_source.register(ast_.RelationOp)
def _(ast: ast_.BinaryOp | ast_.RelationOp, indent: int) -> str:
    left_str = _ast_to_source(ast.left, indent)
    right_str = _ast_to_source(ast.right, indent)
    return f"({left_str} {ast.op_type.to_source()} {right_str})"


@_ast_to_source.register(ast_.UnaryOp)
def _(ast: ast_.UnaryOp, indent: int) -> str:
    if ast.op_type == ast_.UnaryOperator.INVERSE:
        return f"{_ast_to_source(ast.value, indent)}{ast.op_type.to_source()}"
    return f"{ast.op_type.to_source()}{_ast_to_source(ast.value, indent)}"


@_ast_to_source.register(ast_.ListOp)
def _(ast: ast_.ListOp, indent: int) -> str:
    if len(ast.items) == 0:
        return ""
    if len(ast.items) == 1:
        return _ast_to_source(ast.items[0], indent)
    return "(" + f" {ast.op_type.to_source()} ".join(_ast_to_source(item, indent) for item in ast.items) + ")"


@_ast_to_source.register(ast_.Quantifier3)
def _(ast: ast_.Quantifier3, indent: int) -> str:
    quantifier = _ast_to_source(ast.body, indent)

    if ast.op_type.is_collection_operator():  # collection operators need to wrap the quantification
        l_wrapper, r_wrapper = tuple(ast.op_type.to_source())
        quantifier = f"{l_wrapper}{quantifier}{r_wrapper}"
    else:
        quantifier = f"{ast.op_type.to_source()} {quantifier}"
    return quantifier


@_ast_to_source.register(ast_.Generator)
def _(ast: ast_.Generator, indent: int) -> str:
    generator = f"{_ast_to_source(ast.identifiers, indent)} ∈ {_ast_to_source(ast.set_, indent)}"
    if not isinstance(ast.predicate, ast_.True_):
        generator += f" · {_ast_to_source(ast.predicate, indent)}"
    return generator


@_ast_to_source.register(ast_.QuantifierBody)
@_ast_to_source.register(ast_.IterBody)
def _(ast: ast_.QuantifierBody | ast_.IterBody, indent: int) -> str:
    generators = ", ".join(_ast_to_source(gen, indent) for gen in ast.generators)
    if isinstance(ast.end_or_branch, list):
        # To account for no initial generators, we conditionally add a comma between generators and branches
        if generators:
            generators += ", "
        branches = ") ` (".join(_ast_to_source(branch, indent) for branch in ast.end_or_branch)
        return f"{generators}({branches})"
    return f"{generators} | {_ast_to_source(ast.end_or_branch, indent)}"


@_ast_to_source.register(ast_.Fold)
def _(ast: ast_.Fold, indent: int) -> str:
    init_accumulator = _ast_to_source(ast.accumulator_init, indent)
    body = _ast_to_source(ast.quantifier_body, indent)
    return f"fold {init_accumulator} : {body}"


@_ast_to_source.register(ast_.IterGenerator)
def _(ast: ast_.IterGenerator, indent: int) -> str:
    assignments = "; ".join(_ast_to_source(assignment, indent) for assignment in ast.assignments)
    return f"{_ast_to_source(ast.generator, indent)} : {assignments}"


@_ast_to_source.register(ast_.IterBodyEnd)
def _(ast: ast_.IterBodyEnd, indent: int) -> str:
    body = _ast_to_source(ast.body, indent)
    return_value = _ast_to_source(ast.return_value, indent)
    return f"→ {return_value} | {body}"


@_ast_to_source.register(ast_.Iter)
def _(ast: ast_.Iter, indent: int) -> str:
    return f"iter {ast.body}"


@_ast_to_source.register(ast_.Enumeration)
def _(ast: ast_.Enumeration, indent: int) -> str:
    l_wrapper, r_wrapper = tuple(ast.op_type.to_source())
    return f"{l_wrapper}{', '.join(_ast_to_source(item, indent) for item in ast.items)}{r_wrapper}"


@_ast_to_source.register(ast_.TupleLiteral)
def _(ast: ast_.TupleLiteral, indent: int) -> str:
    if len(ast.items) == 1:
        return f"({_ast_to_source(ast.items[0], indent)},)"
    return f"({', '.join(_ast_to_source(item, indent) for item in ast.items)})"


@_ast_to_source.register(ast_.Type_)
def _(ast: ast_.Type_, indent: int) -> str:
    generic_parameters = [_ast_to_source(param, indent) for param in ast.generics]
    if not generic_parameters:
        return _ast_to_source(ast.type_, indent)
    return f"{_ast_to_source(ast.type_, indent)}[{', '.join(generic_parameters)}]"


@_ast_to_source.register(ast_.LambdaDef)
def _(ast: ast_.LambdaDef, indent: int) -> str:
    args_str = _ast_to_source(ast.params, indent)
    predicate_str = _ast_to_source(ast.predicate, indent)
    expression_str = _ast_to_source(ast.expression, indent)
    return f"λ {args_str} · {predicate_str} | {expression_str}"


@_ast_to_source.register(ast_.RecordAccess)
def _(ast: ast_.RecordAccess, indent: int) -> str:
    return f"{_ast_to_source(ast.record, indent)}.{_ast_to_source(ast.field_name, indent)}"


@_ast_to_source.register(ast_.Call)
def _(ast: ast_.Call, indent: int) -> str:
    args_str = ", ".join(_ast_to_source(arg, indent) for arg in ast.args)
    return f"{_ast_to_source(ast.target, indent)}({args_str})"


@_ast_to_source.register(ast_.Image)
def _(ast: ast_.Image, indent: int) -> str:
    args_str = ", ".join(_ast_to_source(arg, indent) for arg in ast.indices)
    return f"{_ast_to_source(ast.target, indent)}[{args_str}]"


@_ast_to_source.register(ast_.TypedName)
def _(ast: ast_.TypedName, indent: int) -> str:
    return f"{_ast_to_source(ast.name, indent)}: {_ast_to_source(ast.type_, indent)}"


@_ast_to_source.register(ast_.TraitApplication)
def _(ast: ast_.TraitApplication, indent: int) -> str:
    target = _ast_to_source(ast.target, indent)
    if ast.traits:
        indentation = "\t" * (indent + 1)
        with_clause_str = f"\n{indentation}with" + f"\n{indentation}with".join(_ast_to_source(clause, indent + 1) for clause in ast.traits)
        return f"{target}{with_clause_str}"
    return target


@_ast_to_source.register(ast_.Assignment)
def _(ast: ast_.Assignment, indent: int) -> str:
    if ast.choice_assignment:
        return f"{_ast_to_source(ast.target, indent)} :∈ {_ast_to_source(ast.value, indent)}"
    return f"{_ast_to_source(ast.target, indent)} := {_ast_to_source(ast.value, indent)}"


@_ast_to_source.register(ast_.Return)
def _(ast: ast_.Return, indent: int) -> str:
    if isinstance(ast.value, ast_.None_):
        return "return"
    return f"return {_ast_to_source(ast.value, indent)}"


@_ast_to_source.register(ast_.ControlFlowStmt)
def _(ast: ast_.ControlFlowStmt, indent: int) -> str:
    return ast.op_type.to_source()


@_ast_to_source.register(ast_.Statements)
def _(ast: ast_.Statements, indent: int) -> str:
    return f"\n{'\t'*indent}".join(_ast_to_source(item, indent) for item in ast.items)


@_ast_to_source.register(ast_.Else)
def _(ast: ast_.Else, indent: int) -> str:
    return f"else:\n\t{'\t'*indent}{_ast_to_source(ast.body, indent+1)}\n"


@_ast_to_source.register(ast_.If)
def _(ast: ast_.If, indent: int) -> str:
    ret = f"if {_ast_to_source(ast.condition, indent)}:\n"
    ret += f"{'\t' * (indent + 1)}{_ast_to_source(ast.body, indent + 1)}"
    ret += "\n"
    if isinstance(ast.else_body, ast_.None_):
        return ret
    ret += _ast_to_source(ast.else_body, indent)
    return ret


@_ast_to_source.register(ast_.ElseIf)
def _(ast: ast_.ElseIf, indent: int) -> str:
    ret = f"else if {_ast_to_source(ast.condition, indent)}:\n"
    ret += f"{'\t' * (indent + 1)}{_ast_to_source(ast.body, indent + 1)}"
    ret += "\n"
    if isinstance(ast.else_body, ast_.None_):
        return ret
    ret += _ast_to_source(ast.else_body, indent)
    return ret


@_ast_to_source.register(ast_.For)
def _(ast: ast_.For, indent: int) -> str:
    iterable_str = _ast_to_source(ast.iterable, indent)
    names_str = _ast_to_source(ast.iterable_names, indent)
    body_str = _ast_to_source(ast.body, indent + 1)
    return f"for {names_str} in {iterable_str}:\n{'\t' * (indent + 1)}{body_str}\n"


@_ast_to_source.register(ast_.While)
def _(ast: ast_.While, indent: int) -> str:
    condition_str = _ast_to_source(ast.condition, indent)
    body_str = _ast_to_source(ast.body, indent + 1)
    return f"while {condition_str}:\n{'\t' * (indent + 1)}{body_str}\n"


@_ast_to_source.register(ast_.RecordDefIdentifier)
def _(ast: ast_.RecordDefIdentifier, indent: int) -> str:
    items_str = f"\n{'\t'*(indent + 1)}".join(_ast_to_source(item, indent + 1) for item in ast.items)
    return f"struct {_ast_to_source(ast.name, indent)}({items_str})"


@_ast_to_source.register(ast_.ProcedureDefIdentifier)
def _(ast: ast_.ProcedureDefIdentifier, indent: int) -> str:
    args_str = f",\n{'\t'*(indent + 1)}".join(_ast_to_source(arg, indent + 1) for arg in ast.args)
    body_str = _ast_to_source(ast.body, indent + 1)
    return_type_str = _ast_to_source(ast.return_type, indent)
    return f"def {_ast_to_source(ast.name, indent)}(\n{args_str}\n) -> {return_type_str}:\n{'\t' * (indent + 1)}{body_str}\n"


@_ast_to_source.register(ast_.Import)
def _(ast: ast_.Import, indent: int) -> str:
    match ast.operator:
        case ast_.ImportOperator.ALL_NAMES:
            return f"from {ast.module_file_path} import *"
        case ast_.ImportOperator.MODULE_NAME:
            return f"import {ast.module_file_path}"
        case ast_.ImportOperator.SPECIFIC_NAMES:
            return f"from {ast.module_file_path} import {', '.join(ast.import_objects)}"


@_ast_to_source.register(ast_.Start)
def _(ast: ast_.Start, indent: int) -> str:
    return _ast_to_source(ast.body, indent) if ast.body else ""


@_ast_to_source.register(ast_.GeneratorSelection)
@_ast_to_source.register(ast_.CombinedGeneratorSelection)
@_ast_to_source.register(ast_.SingleGeneratorSelection)
def _(ast: ast_.GeneratorSelection | ast_.CombinedGeneratorSelection | ast_.SingleGeneratorSelection, indent: int) -> str:
    return _ast_to_source(ast.flatten(), indent)


@_ast_to_source.register(ast_.Loop)
def _(ast: ast_.Loop, indent: int) -> str:
    predicate = _ast_to_source(ast.predicate, indent)
    body = _ast_to_source(ast.body, indent + 1)
    return f"loop {predicate}:\n{'\t' * (indent + 1)}{body}\n"


def ast_to_debug_string(
    ast: ast_.ASTNode,
    ignore_fields: list[str] | None = None,
) -> str:
    """Pretty print the AST node with JSON-like indentation for debugging."""
    if ignore_fields is None:
        ignore_fields = []
    # TODO check should indent=2?
    return _ast_to_debug_string(ast, ignore_fields, 0)


def _ast_to_debug_string(
    ast: ast_.ASTNode,
    ignore_fields: list[str],
    indent: int,
) -> str:
    if ast.__class__.__name__ in ignore_fields:
        indent_ = ""
        indent -= 2
        ret = ""
    else:
        ret = f"{ast.__class__.__name__}:\n"
        indent_ = indent * " "

    for f in fields(ast):
        field_value = getattr(ast, f.name)

        if isinstance(field_value, ast_.ASTNode):
            if len(fields(ast)) == 1:
                ret += f"{indent_}{_ast_to_debug_string(field_value, ignore_fields, indent + 2)}"
            else:
                ret += f"{indent_}{f.name}={_ast_to_debug_string(field_value,ignore_fields,indent + 2)}"

            continue

        if isinstance(field_value, list):
            ret += f"{indent_}[\n"
            for item in field_value:
                if isinstance(item, ast_.ASTNode):
                    ret += f"{indent_}{_ast_to_debug_string(item,ignore_fields,indent + 2)}"
                else:
                    ret += f"{indent_}    {item}\n"
            ret += f"{indent_}]\n"
            continue

        ret += f"- {indent_}{f.name}: {field_value}\n"
    return ret
